fix(stm32mp1): add missing platform.h include
This includes the functions definitions, and avoids sparse warnings:
plat/st/stm32mp1/plat_image_load.c:13:6: warning:
 symbol 'plat_flush_next_bl_params' was not declared.
 Should it be static?
plat/st/stm32mp1/plat_image_load.c:21:16: warning:
 symbol 'plat_get_bl_image_load_info' was not declared.
 Should it be static?
plat/st/stm32mp1/plat_image_load.c:29:13: warning:
 symbol 'plat_get_next_bl_params' was not declared.
 Should it be static?

The issue was also found when enabling -Wmissing-prototypes warning:
plat/st/stm32mp1/plat_image_load.c:13:6: error:
 no previous prototype for 'plat_flush_next_bl_params'
 [-Werror=missing-prototypes]
   13 | void plat_flush_next_bl_params(void)
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~
plat/st/stm32mp1/plat_image_load.c:21:17: error:
 no previous prototype for 'plat_get_bl_image_load_info'
 [-Werror=missing-prototypes]
   21 | bl_load_info_t *plat_get_bl_image_load_info(void)
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
plat/st/stm32mp1/plat_image_load.c:29:14: error:
 no previous prototype for 'plat_get_next_bl_params'
 [-Werror=missing-prototypes]
   29 | bl_params_t *plat_get_next_bl_params(void)
      |              ^~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Yann Gautier <yann.gautier@st.com>
Change-Id: I0bb3052f6efd888462eab2fd8f18862e7fbf02b9