plat: renesas: rz: tbbr_cot: add missing header cot_def.h
There is an issue when compiling RZ/G2L Series with security
mode:
| plat/renesas/rz/common/drivers/auth/tbbr/tbbr_cot.c:52:49: error: 'COT_MAX_VERIFIED_PARAMS' undeclared here (not in a function)
|   .authenticated_data = (const auth_param_desc_t[COT_MAX_VERIFIED_PARAMS]) {

Add missing header cot_def.h to avoid this issue.

Signed-off-by: Hien Huynh <hien.huynh.px@renesas.com>